# Generated by Django 3.2.4 on 2021-06-30 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chekpolis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('agent_id', models.PositiveIntegerField()),
                ('polis_sery', models.CharField(max_length=15)),
                ('polis_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('agent_id', models.PositiveIntegerField()),
                ('agent_phone', models.CharField(max_length=15)),
                ('transaction_id', models.IntegerField()),
                ('period_begin', models.DateField()),
                ('product_id', models.PositiveIntegerField()),
                ('client_name', models.CharField(blank=True, max_length=512, null=True)),
                ('client_address', models.CharField(blank=True, max_length=512, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('client_passport', models.CharField(blank=True, max_length=15, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=512, null=True)),
                ('object', models.TextField(blank=True, null=True)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=30)),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('agent_id', models.PositiveIntegerField()),
                ('agent_phone', models.CharField(max_length=15)),
                ('transaction_id', models.IntegerField()),
                ('period_begin', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_id', models.IntegerField()),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=30)),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=30)),
                ('insurance_liability', models.DecimalField(decimal_places=2, max_digits=30)),
                ('polis_seria', models.CharField(blank=True, max_length=15, null=True)),
                ('polis_number', models.IntegerField(blank=True, null=True)),
                ('policy_status', models.CharField(blank=True, max_length=100, null=True)),
                ('polis_owner', models.TextField(blank=True, null=True)),
                ('polis_begin', models.DateField(blank=True, null=True)),
                ('polis_end', models.DateField(blank=True, null=True)),
                ('term_date', models.DateField(blank=True, null=True)),
                ('term_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('term_note', models.TextField(blank=True, null=True)),
                ('agent_id', models.PositiveIntegerField()),
                ('agent_phone', models.CharField(max_length=15)),
                ('product_id', models.PositiveIntegerField()),
                ('client_name', models.CharField(blank=True, max_length=512, null=True)),
                ('client_address', models.CharField(blank=True, max_length=512, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('client_passport', models.CharField(blank=True, max_length=15, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=512, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('result_message', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('agent_id', models.PositiveIntegerField()),
                ('polis_sery', models.CharField(max_length=15)),
                ('polis_number', models.IntegerField()),
                ('term_date', models.DateField()),
                ('term_note', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
