# Generated by Django 3.2.4 on 2021-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='policy_status',
            new_name='polis_status',
        ),
    ]
