# Generated by Django 3.2.4 on 2021-06-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_policy_status_report_polis_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='polis_seria',
            new_name='polis_sery',
        ),
    ]
