# Generated by Django 3.2.4 on 2021-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_polis_seria_report_polis_sery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
