# Generated by Django 3.2.4 on 2021-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='media/qrcode/%d%m%Y/'),
        ),
    ]
