# Generated by Django 3.2.4 on 2021-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_report_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
