# Generated by Django 3.2.4 on 2021-07-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
