# Generated by Django 3.2.4 on 2021-07-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210719_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='qrcode',
            field=models.URLField(blank=True, null=True),
        ),
    ]
