# Generated by Django 3.2.4 on 2021-07-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_report_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='qrcode',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
