# Generated by Django 3.2.4 on 2021-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
