# Generated by Django 3.2.4 on 2021-07-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agent_id',
            field=models.PositiveIntegerField(verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='report',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона  агента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Бенифициар'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_passport',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Паспорт клиента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance_cost',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Страховая сумма'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance_liability',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Страховая ответственность'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance_premium',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Страховая премия'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='pdf вариант'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_begin',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер полиса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_owner',
            field=models.TextField(blank=True, null=True, verbose_name='Владелиц'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_sery',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Серия полиса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='polis_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статус полиса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product_id',
            field=models.PositiveIntegerField(verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='report',
            name='qrcode',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='QRCODE'),
        ),
        migrations.AlterField(
            model_name='report',
            name='term_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Сумма расторжения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='term_note',
            field=models.TextField(blank=True, null=True, verbose_name='Причина расторжения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='transaction_id',
            field=models.IntegerField(verbose_name='Транзакция'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
